// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: knode/v1/knode.proto

package knodepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnodeService_AuthenticateUser_FullMethodName   = "/knode.v1.KnodeService/AuthenticateUser"
	KnodeService_ConnectUser_FullMethodName        = "/knode.v1.KnodeService/ConnectUser"
	KnodeService_DisconnectUser_FullMethodName     = "/knode.v1.KnodeService/DisconnectUser"
	KnodeService_ListSessions_FullMethodName       = "/knode.v1.KnodeService/ListSessions"
	KnodeService_EnableCore_FullMethodName         = "/knode.v1.KnodeService/EnableCore"
	KnodeService_DisableCore_FullMethodName        = "/knode.v1.KnodeService/DisableCore"
	KnodeService_CoreStatus_FullMethodName         = "/knode.v1.KnodeService/CoreStatus"
	KnodeService_AllCoreStatuses_FullMethodName    = "/knode.v1.KnodeService/AllCoreStatuses"
	KnodeService_SyncUsers_FullMethodName          = "/knode.v1.KnodeService/SyncUsers"
	KnodeService_SetUserLimits_FullMethodName      = "/knode.v1.KnodeService/SetUserLimits"
	KnodeService_GetTraffic_FullMethodName         = "/knode.v1.KnodeService/GetTraffic"
	KnodeService_GetUserTraffic_FullMethodName     = "/knode.v1.KnodeService/GetUserTraffic"
	KnodeService_ResetTraffic_FullMethodName       = "/knode.v1.KnodeService/ResetTraffic"
	KnodeService_Health_FullMethodName             = "/knode.v1.KnodeService/Health"
	KnodeService_Restart_FullMethodName            = "/knode.v1.KnodeService/Restart"
	KnodeService_OpenPort_FullMethodName           = "/knode.v1.KnodeService/OpenPort"
	KnodeService_ClosePort_FullMethodName          = "/knode.v1.KnodeService/ClosePort"
	KnodeService_ListFirewallRules_FullMethodName  = "/knode.v1.KnodeService/ListFirewallRules"
	KnodeService_SetCertificates_FullMethodName    = "/knode.v1.KnodeService/SetCertificates"
	KnodeService_GetCertInfo_FullMethodName        = "/knode.v1.KnodeService/GetCertInfo"
	KnodeService_GenerateClientCert_FullMethodName = "/knode.v1.KnodeService/GenerateClientCert"
	KnodeService_SyncMTProtoSecrets_FullMethodName = "/knode.v1.KnodeService/SyncMTProtoSecrets"
	KnodeService_SetupTunnel_FullMethodName        = "/knode.v1.KnodeService/SetupTunnel"
	KnodeService_TeardownTunnel_FullMethodName     = "/knode.v1.KnodeService/TeardownTunnel"
	KnodeService_TunnelStatus_FullMethodName       = "/knode.v1.KnodeService/TunnelStatus"
	KnodeService_StreamMetrics_FullMethodName      = "/knode.v1.KnodeService/StreamMetrics"
)

// KnodeServiceClient is the client API for KnodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KnodeService is the main service exposed by knode.
// Panels connect to this service via mTLS + API key to manage VPN cores.
type KnodeServiceClient interface {
	// Authentication
	AuthenticateUser(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Sessions
	ConnectUser(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	DisconnectUser(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// Cores
	EnableCore(ctx context.Context, in *EnableCoreRequest, opts ...grpc.CallOption) (*EnableCoreResponse, error)
	DisableCore(ctx context.Context, in *DisableCoreRequest, opts ...grpc.CallOption) (*DisableCoreResponse, error)
	CoreStatus(ctx context.Context, in *CoreStatusRequest, opts ...grpc.CallOption) (*CoreStatusResponse, error)
	AllCoreStatuses(ctx context.Context, in *AllCoreStatusesRequest, opts ...grpc.CallOption) (*AllCoreStatusesResponse, error)
	// Users
	SyncUsers(ctx context.Context, in *SyncUsersRequest, opts ...grpc.CallOption) (*SyncUsersResponse, error)
	SetUserLimits(ctx context.Context, in *SetUserLimitsRequest, opts ...grpc.CallOption) (*SetUserLimitsResponse, error)
	// Traffic
	GetTraffic(ctx context.Context, in *GetTrafficRequest, opts ...grpc.CallOption) (*TrafficReport, error)
	GetUserTraffic(ctx context.Context, in *GetUserTrafficRequest, opts ...grpc.CallOption) (*UserTrafficResponse, error)
	ResetTraffic(ctx context.Context, in *ResetTrafficRequest, opts ...grpc.CallOption) (*ResetTrafficResponse, error)
	// System
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error)
	// Firewall
	OpenPort(ctx context.Context, in *OpenPortRequest, opts ...grpc.CallOption) (*OpenPortResponse, error)
	ClosePort(ctx context.Context, in *ClosePortRequest, opts ...grpc.CallOption) (*ClosePortResponse, error)
	ListFirewallRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	// Certificates
	SetCertificates(ctx context.Context, in *SetCertsRequest, opts ...grpc.CallOption) (*SetCertsResponse, error)
	GetCertInfo(ctx context.Context, in *GetCertInfoRequest, opts ...grpc.CallOption) (*CertInfoResponse, error)
	GenerateClientCert(ctx context.Context, in *GenerateClientCertRequest, opts ...grpc.CallOption) (*GenerateClientCertResponse, error)
	// MTProto per-user secret management
	SyncMTProtoSecrets(ctx context.Context, in *SyncMTProtoSecretsRequest, opts ...grpc.CallOption) (*SyncMTProtoSecretsResponse, error)
	// Outbound Tunnels
	SetupTunnel(ctx context.Context, in *SetupTunnelRequest, opts ...grpc.CallOption) (*SetupTunnelResponse, error)
	TeardownTunnel(ctx context.Context, in *TeardownTunnelRequest, opts ...grpc.CallOption) (*TeardownTunnelResponse, error)
	TunnelStatus(ctx context.Context, in *TunnelStatusRequest, opts ...grpc.CallOption) (*TunnelStatusResponse, error)
	// Metrics Stream (server-side streaming)
	StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsEvent], error)
}

type knodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnodeServiceClient(cc grpc.ClientConnInterface) KnodeServiceClient {
	return &knodeServiceClient{cc}
}

func (c *knodeServiceClient) AuthenticateUser(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, KnodeService_AuthenticateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) ConnectUser(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, KnodeService_ConnectUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) DisconnectUser(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, KnodeService_DisconnectUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, KnodeService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) EnableCore(ctx context.Context, in *EnableCoreRequest, opts ...grpc.CallOption) (*EnableCoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableCoreResponse)
	err := c.cc.Invoke(ctx, KnodeService_EnableCore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) DisableCore(ctx context.Context, in *DisableCoreRequest, opts ...grpc.CallOption) (*DisableCoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableCoreResponse)
	err := c.cc.Invoke(ctx, KnodeService_DisableCore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) CoreStatus(ctx context.Context, in *CoreStatusRequest, opts ...grpc.CallOption) (*CoreStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoreStatusResponse)
	err := c.cc.Invoke(ctx, KnodeService_CoreStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) AllCoreStatuses(ctx context.Context, in *AllCoreStatusesRequest, opts ...grpc.CallOption) (*AllCoreStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllCoreStatusesResponse)
	err := c.cc.Invoke(ctx, KnodeService_AllCoreStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) SyncUsers(ctx context.Context, in *SyncUsersRequest, opts ...grpc.CallOption) (*SyncUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncUsersResponse)
	err := c.cc.Invoke(ctx, KnodeService_SyncUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) SetUserLimits(ctx context.Context, in *SetUserLimitsRequest, opts ...grpc.CallOption) (*SetUserLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserLimitsResponse)
	err := c.cc.Invoke(ctx, KnodeService_SetUserLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) GetTraffic(ctx context.Context, in *GetTrafficRequest, opts ...grpc.CallOption) (*TrafficReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrafficReport)
	err := c.cc.Invoke(ctx, KnodeService_GetTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) GetUserTraffic(ctx context.Context, in *GetUserTrafficRequest, opts ...grpc.CallOption) (*UserTrafficResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserTrafficResponse)
	err := c.cc.Invoke(ctx, KnodeService_GetUserTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) ResetTraffic(ctx context.Context, in *ResetTrafficRequest, opts ...grpc.CallOption) (*ResetTrafficResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetTrafficResponse)
	err := c.cc.Invoke(ctx, KnodeService_ResetTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, KnodeService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartResponse)
	err := c.cc.Invoke(ctx, KnodeService_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) OpenPort(ctx context.Context, in *OpenPortRequest, opts ...grpc.CallOption) (*OpenPortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenPortResponse)
	err := c.cc.Invoke(ctx, KnodeService_OpenPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) ClosePort(ctx context.Context, in *ClosePortRequest, opts ...grpc.CallOption) (*ClosePortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClosePortResponse)
	err := c.cc.Invoke(ctx, KnodeService_ClosePort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) ListFirewallRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, KnodeService_ListFirewallRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) SetCertificates(ctx context.Context, in *SetCertsRequest, opts ...grpc.CallOption) (*SetCertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCertsResponse)
	err := c.cc.Invoke(ctx, KnodeService_SetCertificates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) GetCertInfo(ctx context.Context, in *GetCertInfoRequest, opts ...grpc.CallOption) (*CertInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertInfoResponse)
	err := c.cc.Invoke(ctx, KnodeService_GetCertInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) GenerateClientCert(ctx context.Context, in *GenerateClientCertRequest, opts ...grpc.CallOption) (*GenerateClientCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateClientCertResponse)
	err := c.cc.Invoke(ctx, KnodeService_GenerateClientCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) SyncMTProtoSecrets(ctx context.Context, in *SyncMTProtoSecretsRequest, opts ...grpc.CallOption) (*SyncMTProtoSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncMTProtoSecretsResponse)
	err := c.cc.Invoke(ctx, KnodeService_SyncMTProtoSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) SetupTunnel(ctx context.Context, in *SetupTunnelRequest, opts ...grpc.CallOption) (*SetupTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupTunnelResponse)
	err := c.cc.Invoke(ctx, KnodeService_SetupTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) TeardownTunnel(ctx context.Context, in *TeardownTunnelRequest, opts ...grpc.CallOption) (*TeardownTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeardownTunnelResponse)
	err := c.cc.Invoke(ctx, KnodeService_TeardownTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) TunnelStatus(ctx context.Context, in *TunnelStatusRequest, opts ...grpc.CallOption) (*TunnelStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TunnelStatusResponse)
	err := c.cc.Invoke(ctx, KnodeService_TunnelStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knodeServiceClient) StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KnodeService_ServiceDesc.Streams[0], KnodeService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMetricsRequest, MetricsEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KnodeService_StreamMetricsClient = grpc.ServerStreamingClient[MetricsEvent]

// KnodeServiceServer is the server API for KnodeService service.
// All implementations must embed UnimplementedKnodeServiceServer
// for forward compatibility.
//
// KnodeService is the main service exposed by knode.
// Panels connect to this service via mTLS + API key to manage VPN cores.
type KnodeServiceServer interface {
	// Authentication
	AuthenticateUser(context.Context, *AuthRequest) (*AuthResponse, error)
	// Sessions
	ConnectUser(context.Context, *ConnectRequest) (*ConnectResponse, error)
	DisconnectUser(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// Cores
	EnableCore(context.Context, *EnableCoreRequest) (*EnableCoreResponse, error)
	DisableCore(context.Context, *DisableCoreRequest) (*DisableCoreResponse, error)
	CoreStatus(context.Context, *CoreStatusRequest) (*CoreStatusResponse, error)
	AllCoreStatuses(context.Context, *AllCoreStatusesRequest) (*AllCoreStatusesResponse, error)
	// Users
	SyncUsers(context.Context, *SyncUsersRequest) (*SyncUsersResponse, error)
	SetUserLimits(context.Context, *SetUserLimitsRequest) (*SetUserLimitsResponse, error)
	// Traffic
	GetTraffic(context.Context, *GetTrafficRequest) (*TrafficReport, error)
	GetUserTraffic(context.Context, *GetUserTrafficRequest) (*UserTrafficResponse, error)
	ResetTraffic(context.Context, *ResetTrafficRequest) (*ResetTrafficResponse, error)
	// System
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Restart(context.Context, *RestartRequest) (*RestartResponse, error)
	// Firewall
	OpenPort(context.Context, *OpenPortRequest) (*OpenPortResponse, error)
	ClosePort(context.Context, *ClosePortRequest) (*ClosePortResponse, error)
	ListFirewallRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	// Certificates
	SetCertificates(context.Context, *SetCertsRequest) (*SetCertsResponse, error)
	GetCertInfo(context.Context, *GetCertInfoRequest) (*CertInfoResponse, error)
	GenerateClientCert(context.Context, *GenerateClientCertRequest) (*GenerateClientCertResponse, error)
	// MTProto per-user secret management
	SyncMTProtoSecrets(context.Context, *SyncMTProtoSecretsRequest) (*SyncMTProtoSecretsResponse, error)
	// Outbound Tunnels
	SetupTunnel(context.Context, *SetupTunnelRequest) (*SetupTunnelResponse, error)
	TeardownTunnel(context.Context, *TeardownTunnelRequest) (*TeardownTunnelResponse, error)
	TunnelStatus(context.Context, *TunnelStatusRequest) (*TunnelStatusResponse, error)
	// Metrics Stream (server-side streaming)
	StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[MetricsEvent]) error
	mustEmbedUnimplementedKnodeServiceServer()
}

// UnimplementedKnodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnodeServiceServer struct{}

func (UnimplementedKnodeServiceServer) AuthenticateUser(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthenticateUser not implemented")
}
func (UnimplementedKnodeServiceServer) ConnectUser(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectUser not implemented")
}
func (UnimplementedKnodeServiceServer) DisconnectUser(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectUser not implemented")
}
func (UnimplementedKnodeServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedKnodeServiceServer) EnableCore(context.Context, *EnableCoreRequest) (*EnableCoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableCore not implemented")
}
func (UnimplementedKnodeServiceServer) DisableCore(context.Context, *DisableCoreRequest) (*DisableCoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableCore not implemented")
}
func (UnimplementedKnodeServiceServer) CoreStatus(context.Context, *CoreStatusRequest) (*CoreStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CoreStatus not implemented")
}
func (UnimplementedKnodeServiceServer) AllCoreStatuses(context.Context, *AllCoreStatusesRequest) (*AllCoreStatusesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllCoreStatuses not implemented")
}
func (UnimplementedKnodeServiceServer) SyncUsers(context.Context, *SyncUsersRequest) (*SyncUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncUsers not implemented")
}
func (UnimplementedKnodeServiceServer) SetUserLimits(context.Context, *SetUserLimitsRequest) (*SetUserLimitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserLimits not implemented")
}
func (UnimplementedKnodeServiceServer) GetTraffic(context.Context, *GetTrafficRequest) (*TrafficReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraffic not implemented")
}
func (UnimplementedKnodeServiceServer) GetUserTraffic(context.Context, *GetUserTrafficRequest) (*UserTrafficResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTraffic not implemented")
}
func (UnimplementedKnodeServiceServer) ResetTraffic(context.Context, *ResetTrafficRequest) (*ResetTrafficResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetTraffic not implemented")
}
func (UnimplementedKnodeServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedKnodeServiceServer) Restart(context.Context, *RestartRequest) (*RestartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedKnodeServiceServer) OpenPort(context.Context, *OpenPortRequest) (*OpenPortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenPort not implemented")
}
func (UnimplementedKnodeServiceServer) ClosePort(context.Context, *ClosePortRequest) (*ClosePortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClosePort not implemented")
}
func (UnimplementedKnodeServiceServer) ListFirewallRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFirewallRules not implemented")
}
func (UnimplementedKnodeServiceServer) SetCertificates(context.Context, *SetCertsRequest) (*SetCertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCertificates not implemented")
}
func (UnimplementedKnodeServiceServer) GetCertInfo(context.Context, *GetCertInfoRequest) (*CertInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCertInfo not implemented")
}
func (UnimplementedKnodeServiceServer) GenerateClientCert(context.Context, *GenerateClientCertRequest) (*GenerateClientCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateClientCert not implemented")
}
func (UnimplementedKnodeServiceServer) SyncMTProtoSecrets(context.Context, *SyncMTProtoSecretsRequest) (*SyncMTProtoSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncMTProtoSecrets not implemented")
}
func (UnimplementedKnodeServiceServer) SetupTunnel(context.Context, *SetupTunnelRequest) (*SetupTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetupTunnel not implemented")
}
func (UnimplementedKnodeServiceServer) TeardownTunnel(context.Context, *TeardownTunnelRequest) (*TeardownTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TeardownTunnel not implemented")
}
func (UnimplementedKnodeServiceServer) TunnelStatus(context.Context, *TunnelStatusRequest) (*TunnelStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TunnelStatus not implemented")
}
func (UnimplementedKnodeServiceServer) StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[MetricsEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedKnodeServiceServer) mustEmbedUnimplementedKnodeServiceServer() {}
func (UnimplementedKnodeServiceServer) testEmbeddedByValue()                      {}

// UnsafeKnodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnodeServiceServer will
// result in compilation errors.
type UnsafeKnodeServiceServer interface {
	mustEmbedUnimplementedKnodeServiceServer()
}

func RegisterKnodeServiceServer(s grpc.ServiceRegistrar, srv KnodeServiceServer) {
	// If the following call panics, it indicates UnimplementedKnodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnodeService_ServiceDesc, srv)
}

func _KnodeService_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).AuthenticateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_AuthenticateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).AuthenticateUser(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_ConnectUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).ConnectUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_ConnectUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).ConnectUser(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_DisconnectUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).DisconnectUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_DisconnectUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).DisconnectUser(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_EnableCore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableCoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).EnableCore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_EnableCore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).EnableCore(ctx, req.(*EnableCoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_DisableCore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableCoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).DisableCore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_DisableCore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).DisableCore(ctx, req.(*DisableCoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_CoreStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).CoreStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_CoreStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).CoreStatus(ctx, req.(*CoreStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_AllCoreStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllCoreStatusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).AllCoreStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_AllCoreStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).AllCoreStatuses(ctx, req.(*AllCoreStatusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_SyncUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).SyncUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_SyncUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).SyncUsers(ctx, req.(*SyncUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_SetUserLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).SetUserLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_SetUserLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).SetUserLimits(ctx, req.(*SetUserLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_GetTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).GetTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_GetTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).GetTraffic(ctx, req.(*GetTrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_GetUserTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).GetUserTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_GetUserTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).GetUserTraffic(ctx, req.(*GetUserTrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_ResetTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetTrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).ResetTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_ResetTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).ResetTraffic(ctx, req.(*ResetTrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).Restart(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_OpenPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).OpenPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_OpenPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).OpenPort(ctx, req.(*OpenPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_ClosePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).ClosePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_ClosePort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).ClosePort(ctx, req.(*ClosePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_ListFirewallRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).ListFirewallRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_ListFirewallRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).ListFirewallRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_SetCertificates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).SetCertificates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_SetCertificates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).SetCertificates(ctx, req.(*SetCertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_GetCertInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).GetCertInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_GetCertInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).GetCertInfo(ctx, req.(*GetCertInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_GenerateClientCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateClientCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).GenerateClientCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_GenerateClientCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).GenerateClientCert(ctx, req.(*GenerateClientCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_SyncMTProtoSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMTProtoSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).SyncMTProtoSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_SyncMTProtoSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).SyncMTProtoSecrets(ctx, req.(*SyncMTProtoSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_SetupTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).SetupTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_SetupTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).SetupTunnel(ctx, req.(*SetupTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_TeardownTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeardownTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).TeardownTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_TeardownTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).TeardownTunnel(ctx, req.(*TeardownTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_TunnelStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnodeServiceServer).TunnelStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnodeService_TunnelStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnodeServiceServer).TunnelStatus(ctx, req.(*TunnelStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnodeService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KnodeServiceServer).StreamMetrics(m, &grpc.GenericServerStream[StreamMetricsRequest, MetricsEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KnodeService_StreamMetricsServer = grpc.ServerStreamingServer[MetricsEvent]

// KnodeService_ServiceDesc is the grpc.ServiceDesc for KnodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knode.v1.KnodeService",
	HandlerType: (*KnodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateUser",
			Handler:    _KnodeService_AuthenticateUser_Handler,
		},
		{
			MethodName: "ConnectUser",
			Handler:    _KnodeService_ConnectUser_Handler,
		},
		{
			MethodName: "DisconnectUser",
			Handler:    _KnodeService_DisconnectUser_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _KnodeService_ListSessions_Handler,
		},
		{
			MethodName: "EnableCore",
			Handler:    _KnodeService_EnableCore_Handler,
		},
		{
			MethodName: "DisableCore",
			Handler:    _KnodeService_DisableCore_Handler,
		},
		{
			MethodName: "CoreStatus",
			Handler:    _KnodeService_CoreStatus_Handler,
		},
		{
			MethodName: "AllCoreStatuses",
			Handler:    _KnodeService_AllCoreStatuses_Handler,
		},
		{
			MethodName: "SyncUsers",
			Handler:    _KnodeService_SyncUsers_Handler,
		},
		{
			MethodName: "SetUserLimits",
			Handler:    _KnodeService_SetUserLimits_Handler,
		},
		{
			MethodName: "GetTraffic",
			Handler:    _KnodeService_GetTraffic_Handler,
		},
		{
			MethodName: "GetUserTraffic",
			Handler:    _KnodeService_GetUserTraffic_Handler,
		},
		{
			MethodName: "ResetTraffic",
			Handler:    _KnodeService_ResetTraffic_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _KnodeService_Health_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _KnodeService_Restart_Handler,
		},
		{
			MethodName: "OpenPort",
			Handler:    _KnodeService_OpenPort_Handler,
		},
		{
			MethodName: "ClosePort",
			Handler:    _KnodeService_ClosePort_Handler,
		},
		{
			MethodName: "ListFirewallRules",
			Handler:    _KnodeService_ListFirewallRules_Handler,
		},
		{
			MethodName: "SetCertificates",
			Handler:    _KnodeService_SetCertificates_Handler,
		},
		{
			MethodName: "GetCertInfo",
			Handler:    _KnodeService_GetCertInfo_Handler,
		},
		{
			MethodName: "GenerateClientCert",
			Handler:    _KnodeService_GenerateClientCert_Handler,
		},
		{
			MethodName: "SyncMTProtoSecrets",
			Handler:    _KnodeService_SyncMTProtoSecrets_Handler,
		},
		{
			MethodName: "SetupTunnel",
			Handler:    _KnodeService_SetupTunnel_Handler,
		},
		{
			MethodName: "TeardownTunnel",
			Handler:    _KnodeService_TeardownTunnel_Handler,
		},
		{
			MethodName: "TunnelStatus",
			Handler:    _KnodeService_TunnelStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _KnodeService_StreamMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "knode/v1/knode.proto",
}
